version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: superapp_postgres
    environment:
      POSTGRES_USER: superapp_user
      POSTGRES_PASSWORD: superapp_password
      POSTGRES_DB: superapp_sst
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
